/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_cognito_identity_pool_id: 'us-east-1:27a19859-e980-4b3b-b212-dfcb819e7a1b',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_4mwuhtxYz',
    aws_user_pools_web_client_id: '3qm3pupvji2pk5uc96h0u5g0dg',
    oauth: {}
};


export default awsmobile;
